spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initialSize: 10
      minIdle: 10
      maxActive: 200
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 30000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters
      filters: stat,wall,slf4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  #============== kafka ===================
  # 指定 kafka 代理地址，可以多个
#  kafka:
#    bootstrap-servers: hadoop01:9092,hadoop02:9092,hadoop03:9092
#    # 指定消息 key 和消息体的编解码方式
#    producer.key-serializer: org.apache.kafka.common.serialization.StringSerializer
#    producer.value-serializer: org.apache.kafka.common.serialization.StringSerializer
  #==============短信=======================
  mail:
    host: smtp.163.com
    username: 15735372489@163.com
    password: NHZOLNXAWNTKYGSA
    default-encoding: UTF-8
    # 超时时间（可选）
    properties:
      mail:
        smtp:
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
#==============Redis=======================
  redis:
    database: 0       # Redis数据库索引（默认为0）,如果设置为1，那么存入的key-value都存放在select 1中
    #  127.0.0.1
    host: 127.0.0.1
    port: 6679
    # h1iz6i2dp4redis
    password: h1iz6i2dp4redis
    jedis:
      pool:
        max-wait: 30000   # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-active: 100   # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 20      # 连接池中的最大空闲连接
        min-idle: 0       # 连接池中的最小空闲连接
    timeout: 5000     # 连接超时
#============配置了两个数据源==============
master:
  datasource:
    url: jdbc:clickhouse://hadoop01:8123/default
    username: default # wjr
    password: # v724FzVr
    driverClassName: ru.yandex.clickhouse.ClickHouseDriver
#    url: jdbc:phoenix:hadoop01,hadoop02,hadoop03:2181
#    username:
#    password:
#    driverClassName: org.apache.phoenix.jdbc.PhoenixDriver
cluster:
  datasource:
    url: jdbc:mysql://localhost:3306/lamp?useSSL=false&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
#============分页插件配置=================
pagehelper:
  helperDialect: clickhouse
  auto-runtime-dialect: true
#指定环境，用于swagger判断组
#  profiles:
#    active: dev

#debug: true
